# Configuracion SonarCloud (IE5)
# Reemplaza ORG y PROJECT_KEY por los de tu cuenta SonarCloud.
sonar.projectKey=Ernceaulorquette1_ep3-devops-observabilidad
sonar.organization=ernceaulorquette1

sonar.projectName=ep3-devops-observabilidad
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.host.url=https://sonarcloud.io
# El Quality Gate (configurado en SonarCloud) define los umbrales que,
# al no cumplirse, hacen FALLAR el pipeline (IE6).
